
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/baice/Documents/Softwares/cmake-4.1.0-rc1-windows-x86_64/cmake-4.1.0-rc1-windows-x86_64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
